name: swissisoform
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.10
  - numpy
  - pandas
  - biopython 
  - bioconductor-biomart
  - pip
  - matplotlib
  - requests
  - gql
  - aiohttp
  - gget
  - pip:
      - -e .